version: 2.1
orbs:
    node: circleci/node@7.1
jobs:
    test:
        parameters:
            node-version:
                type: string
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - node/install:
                  node-version: << parameters.node-version >>
            - run:
                  name: Run build
                  command: npm install
            - run:
                  name: Run tests
                  command: npm run test
            - run:
                  name: Verify build
                  command: echo "Build and Test completed successfully!"
workflows:
    build:
        jobs:
            - test:
                  matrix:
                      parameters:
                          node-version: ['20', '22', '24']
